package FullPOS;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.table.TableModel;

/*
 * @author Cyan Froste
 */
public class Print extends javax.swing.JFrame {
    /**
     * Creates new form Print
     */
    public Print() {
        initComponents();
    }
    String NTotal;
    String NPay;
    String NBalance;
    
    public Print(String Total, String Pay, String Balance, TableModel model) {
        initComponents();
        this.NTotal = Total;
        this.NPay = Pay;
        this.NBalance = Balance;
        txtBill.setText(txtBill.getText() + "------------------------------------------\n");
        txtBill.setText(txtBill.getText() + "--\t\t   BILL   \t\t--\n");
        txtBill.setText(txtBill.getText() + "------------------------------------------\n");
        txtBill.setText(txtBill.getText() + "Product\t\tRate\t Qty.\t   Amount\n\n");        
        for(int i=0; i<model.getRowCount(); i++){
            String Pname = (String)model.getValueAt(i, 1);
            String Discount = (String)model.getValueAt(i, 5);
            if(Discount.equals("")){
                    Discount="0";
            }
            int DiscountCalc = Integer.valueOf(Discount);                
            float Rate = Float.valueOf((String)model.getValueAt(i, 2));
            Rate = Rate - (DiscountCalc*Rate)/100;
            String DiscountedRate = String.valueOf(Rate);
            String Qty = (String)model.getValueAt(i, 3);
            String Amount = (String)model.getValueAt(i, 4);
            if(Pname.length() > 7){
                txtBill.setText(txtBill.getText() +Pname+"\t"+DiscountedRate+"\t"+" "+Qty+"\t"+"   "+Amount+"\n");
            }
            else{
                txtBill.setText(txtBill.getText() +Pname+"\t\t"+DiscountedRate+"\t"+" "+Qty+"\t"+"   "+Amount+"\n");            
            }    
        }
        txtBill.setText(txtBill.getText() +"\n\t\t\tTotal:	   "+Total+"\n");
        txtBill.setText(txtBill.getText() +"\t\t\tPaid:	   "+Pay+"\n");
        txtBill.setText(txtBill.getText() +"\t\t\tBalance:   "+Balance+"\n\n");        
        txtBill.setText(txtBill.getText() + "Incl. Taxes and Discounts\n");
        txtBill.setText(txtBill.getText() + "------------------------------------------\n");
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");  
        LocalDateTime now = LocalDateTime.now();
        txtBill.setText(txtBill.getText() + dtf.format(now));
        txtBill.setText(txtBill.getText() + "\n------------------------------------------\n");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtBill = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        exitInvoice = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setOpacity(0.96F);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        txtBill.setColumns(20);
        txtBill.setForeground(new java.awt.Color(51, 51, 51));
        txtBill.setRows(5);
        jScrollPane1.setViewportView(txtBill);

        jLabel2.setFont(new java.awt.Font("Open Sans Extrabold", 0, 24)); // NOI18N
        jLabel2.setText("INVOICE");

        exitInvoice.setFont(new java.awt.Font("Open Sans", 2, 14)); // NOI18N
        exitInvoice.setForeground(new java.awt.Color(255, 51, 0));
        exitInvoice.setText("exit");
        exitInvoice.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitInvoice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitInvoiceMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitInvoice)
                .addGap(21, 21, 21))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(exitInvoice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseClicked

    private void exitInvoiceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitInvoiceMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_exitInvoiceMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Print().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel exitInvoice;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtBill;
    // End of variables declaration//GEN-END:variables
}
